save_data: /scratch/project_2001970/Geometry/onmt/


# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: /scratch/project_2001970/Geometry/en_de_mustc/train.source
        path_tgt: /scratch/project_2001970/Geometry/en_de_mustc/train.target
    valid:
        path_src: /scratch/project_2001970/Geometry/en_de_mustc/val.source
        path_tgt: /scratch/project_2001970/Geometry/en_de_mustc/val.target

# Vocabulary files that were just created
src_vocab: /scratch/project_2001970/Geometry/onmt/mustc.vocab.src
tgt_vocab: /scratch/project_2001970/Geometry/onmt/mustc.vocab.tgt


save_model: /scratch/project_2001970/Geometry/onmt/models/mustc
save_checkpoint_steps: 10000
keep_checkpoint: 10
seed: 3435
train_steps: 500000
valid_steps: 10000
warmup_steps: 8000
report_every: 250


decoder_type: transformer
encoder_type: bert
word_vec_size: 512
rnn_size: 512
layers: 1
transformer_ff: 2048
heads: 8

accum_count: 8
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1

max_generator_batches: 2

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'


world_size: 1
gpu_ranks:
- 0
